import { SKIP_PREFIXES } from "../constants.js";
import type { QueryLogRecord, SkillUsageRecord } from "../types.js";

const NON_USER_QUERY_PREFIXES = [
  "<system_instruction>",
  "<system-instruction>",
  "<system-reminder>",
  "<available-deferred-tools>",
  "<fast_mode_info>",
  "<local-command-caveat>",
  "<local-command-stdout>",
  "<local-command-stderr>",
  "<command-name>",
  "<task-notification>",
  "<teammate-message",
  "[Request interrupted by user for tool use]",
  "[Request interrupted by user]",
  "Base directory for this skill:",
  "This session is being continued from a previous conversation that ran out of context.",
  "USER'S CURRENT MESSAGE (summarize THIS):",
  "CONTEXT:",
  "Completing task",
  "Tool loaded.",
  "Continue from where you left off.",
  "You are an evaluation assistant.",
  "You are a skill description optimizer for an AI agent routing system.",
  "The following skills are available",
  "[SUGGESTION MODE:",
  "Your task is to create a detailed summary of the conversation",
  "You are working inside Conductor,",
  "You are a rigorous skill session evaluator.",
  "You are generating test queries for a coding agent skill.",
] as const;

/**
 * Regex patterns for wrapper/hook pipeline artifacts that are never real user prompts.
 * These fire after prefix checks and cover structured hook callback lines.
 */
const NON_USER_QUERY_PATTERNS = [
  // Hook callback output lines (e.g. "SessionStart:startup hook success: ...")
  // "Stop" excluded from general alternation — too common as English word.
  /^(SessionStart|UserPromptSubmit|PreToolUse|PostToolUse):/,
  // Stop hook callbacks follow a structured shape: "Stop:" + lowercase/callback text
  /^Stop:(session |cleanup |hook |Callback )/,
  // Injected git context blocks
  /^gitStatus:\s/,
  /^<command-(name|message|args)>/i,
  // Exact collaboration control fields. Keep explanatory user sentences such as
  // "Message Type: MESSAGE is shown in the UI" actionable.
  /^Message Type:\s*(?:MESSAGE|FINAL_ANSWER)\s*$/i,
  /^Task name:\s*\/root(?:\/[a-z0-9._-]+)*\s*$/i,
  // A complete sub-agent handoff envelope, not a user prompt that merely quotes
  // one of its field labels.
  /^Message Type:\s*(?:MESSAGE|FINAL_ANSWER)\s*\r?\nTask name:\s*\/root(?:\/[a-z0-9._-]+)*\s*\r?\nSender:\s*[^\r\n]+\s*\r?\nPayload:\s*\r?\n[\s\S]*$/i,
  // Approval-review deltas are generated by Codex and contain untrusted history,
  // not a new user request. Require the full marker structure instead of blocking
  // every prompt that happens to begin with the introductory sentence.
  /^The following is the Codex agent history added since your last approval assessment\.[\s\S]*>>> TRANSCRIPT DELTA START[\s\S]*>>> TRANSCRIPT DELTA END[\s\S]*>>> APPROVAL REQUEST START[\s\S]*>>> APPROVAL REQUEST END\s*$/i,
] as const;

const LEADING_WRAPPED_QUERY_TAGS = [
  "system_instruction",
  "system-instruction",
  "system-reminder",
  "available-deferred-tools",
  "fast_mode_info",
  "task-notification",
  "teammate-message",
  "local-command-caveat",
  "local-command-stdout",
  "local-command-stderr",
  "command-name",
  "command-message",
  "command-args",
  "codex_internal_context",
  "in-app-browser-context",
  "recommended_plugins",
  "environment_context",
  "instructions",
  "subagent_notification",
  "heartbeat",
  "codex_delegation",
] as const;

const LEADING_WRAPPED_QUERY_PATTERNS = [
  // Codex injects the resolved AGENTS.md body under this heading. Requiring the
  // absolute-path heading and paired INSTRUCTIONS block avoids suppressing an
  // ordinary prompt that discusses AGENTS.md instructions.
  /^# AGENTS\.md instructions for \/[^\r\n]+\r?\n\s*<INSTRUCTIONS\b[^>]*>[\s\S]*?<\/INSTRUCTIONS>\s*/i,
] as const;

const SKILL_MAINTENANCE_VERBS = [
  "grade",
  "review",
  "audit",
  "inspect",
  "analyze",
  "analyse",
  "understand",
  "explain",
  "find",
  "locate",
  "update",
  "fix",
  "repair",
  "improve",
  "debug",
  "document",
  "publish api",
] as const;

const SKILL_MAINTENANCE_NOUNS = [
  "skill",
  "skills",
  "readme",
  "docs",
  "documentation",
  "workflow",
  "workflows",
  "reference",
  "references",
  "files",
  "format",
] as const;

function stripLeadingWrappedQueryText(query: string): string {
  let current = query.trim();

  for (;;) {
    let changed = false;

    for (const tag of LEADING_WRAPPED_QUERY_TAGS) {
      const pattern = new RegExp(`^<${tag}\\b[^>]*>[\\s\\S]*?<\\/${tag}>\\s*`, "i");
      const next = current.replace(pattern, "").trim();
      if (next !== current) {
        current = next;
        changed = true;
        break;
      }
    }

    if (changed) continue;

    for (const pattern of LEADING_WRAPPED_QUERY_PATTERNS) {
      const next = current.replace(pattern, "").trim();
      if (next !== current) {
        current = next;
        changed = true;
        break;
      }
    }

    if (!changed) return current;
  }
}

export function extractActionableQueryText(query: string): string | null {
  if (typeof query !== "string") return null;

  const trimmed = query.trim();
  if (!trimmed || trimmed === "-" || trimmed === "(query not found)") return null;

  const candidate = stripLeadingWrappedQueryText(trimmed);
  if (!candidate || candidate === "-" || candidate === "(query not found)") return null;

  const loweredCandidate = candidate.toLowerCase();
  const isBlocked =
    SKIP_PREFIXES.some((prefix) => candidate.startsWith(prefix)) ||
    NON_USER_QUERY_PREFIXES.some((prefix) => loweredCandidate.startsWith(prefix.toLowerCase())) ||
    NON_USER_QUERY_PATTERNS.some((pattern) => pattern.test(candidate));

  return isBlocked ? null : candidate;
}

function normalizeSkillNameVariants(skillName: string): string[] {
  const trimmed = skillName.trim();
  if (!trimmed) return [];

  const variants = new Set<string>();
  const lower = trimmed.toLowerCase();
  variants.add(lower);
  variants.add(lower.replace(/[-_]+/g, " "));
  variants.add(lower.replace(/[-_\s]+/g, ""));
  variants.add(
    trimmed
      .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
      .replace(/[-_]+/g, " ")
      .toLowerCase(),
  );

  return [...variants].filter(Boolean);
}

export function isLikelySkillMaintenanceQuery(query: string, skillName?: string): boolean {
  const candidate = extractActionableQueryText(query);
  if (!candidate) return false;

  const lowered = candidate.toLowerCase().replace(/\s+/g, " ").trim();
  const mentionsMaintenanceVerb = SKILL_MAINTENANCE_VERBS.some((verb) => lowered.includes(verb));
  const mentionsMaintenanceNoun = SKILL_MAINTENANCE_NOUNS.some((noun) => lowered.includes(noun));
  const mentionsHowItWorks = /\bhow\b[\s\S]{0,80}\bworks?\b/.test(lowered);
  const mentionsSkillName = skillName
    ? normalizeSkillNameVariants(skillName).some(
        (variant) => variant.length > 0 && lowered.includes(variant),
      )
    : false;

  if (mentionsHowItWorks && mentionsSkillName) return true;
  if (mentionsMaintenanceVerb && mentionsMaintenanceNoun) return true;
  if (mentionsMaintenanceVerb && mentionsSkillName) return true;
  return false;
}

export function extractPositiveEvalQueryText(query: string, skillName?: string): string | null {
  const candidate = extractActionableQueryText(query);
  if (!candidate) return null;
  return isLikelySkillMaintenanceQuery(candidate, skillName) ? null : candidate;
}

export function isActionableQueryText(query: string): boolean {
  return extractActionableQueryText(query) !== null;
}

export function filterActionableQueryRecords(queryRecords: QueryLogRecord[]): QueryLogRecord[] {
  const actionable: QueryLogRecord[] = [];

  for (const record of queryRecords) {
    if (record == null) continue;
    const normalizedQuery = extractActionableQueryText((record as QueryLogRecord).query);
    if (!normalizedQuery) continue;
    actionable.push(
      normalizedQuery === record.query ? record : { ...record, query: normalizedQuery },
    );
  }

  return actionable;
}

export function isActionableSkillUsageRecord(record: SkillUsageRecord | null | undefined): boolean {
  if (record == null) return false;
  if (typeof record.skill_name !== "string" || !record.skill_name.trim()) return false;
  if (typeof record.query !== "string") return false;

  const query = record.query.trim();
  if (!query || query === "(query not found)") return false;

  return extractActionableQueryText(query) !== null;
}

export function filterActionableSkillUsageRecords(
  skillRecords: SkillUsageRecord[],
): SkillUsageRecord[] {
  const actionable: SkillUsageRecord[] = [];

  for (const record of skillRecords) {
    const normalizedQuery = extractActionableQueryText(record?.query);
    if (!normalizedQuery) continue;
    actionable.push(
      normalizedQuery === record.query ? record : { ...record, query: normalizedQuery },
    );
  }

  return actionable;
}
