/** Data contracts for the v2 SQLite-backed dashboard API */

// Re-export UI types from shared package
// Re-export dashboard contract types from shared package
export type {
  EvalSnapshot,
  EvidenceEntry,
  EvolutionEntry,
  OrchestrateRunReport,
  OrchestrateRunSkillAction,
  PendingProposal,
  SkillCard,
  SkillHealthStatus,
  UnmatchedQuery,
} from "@selftune/ui/types";

// Types that remain local (only used by pages/hooks, not by shared components)
export type {
  AnalyticsResponse,
  ApplyOnboardingRequest,
  ApplyOnboardingResponse,
  CreatorOverviewStep,
  CreatorLoopNextStep,
  CreatorTestingOverview,
  AttentionCategory,
  AttentionItem,
  AutonomousDecision,
  AutonomyStatus,
  AutonomyStatusLevel,
  CanonicalInvocation,
  CommitRecord,
  CommitSummary,
  CreateSkillSetRequest,
  UpdateSkillSetRequest,
  DeriveSkillSetRequest,
  ExportSkillSetRequest,
  DashboardActionEvent,
  DashboardActionMetrics,
  DashboardActionEventStage,
  DashboardActionName,
  DashboardActionProgress,
  DashboardActionResultSummary,
  DashboardShellResponse,
  DashboardFrontierMember,
  DashboardFrontierState,
  DashboardSearchProvenance,
  DashboardSearchRunSummary,
  DashboardSearchRunView,
  DecisionKind,
  DoctorResult,
  DesktopScheduleFormat,
  DesktopScheduleJob,
  DesktopScheduleJobId,
  DesktopSettingsResponse,
  ExampleRow,
  ExecutionMetrics,
  HealthCheck,
  HealthResponse,
  HealthStatus,
  HarnessConnection,
  HarnessConnectionStatus,
  HarnessId,
  LibrarySnapshot,
  SkillSourceUpdatePreview,
  SkillSourceUpdateReceipt,
  InsightsResponse,
  ReviewInsightRequest,
  DraftInsightRequest,
  OnboardingFeatureId,
  OnboardingInstallResult,
  OnboardingPreferences,
  OrchestrateRunsResponse,
  OverviewPaginatedPayload,
  OverviewPayload,
  OverviewResponse,
  PaginatedResult,
  PaginationCursor,
  PortfolioAuditEntry,
  PortfolioAuditResult,
  PortfolioClassification,
  PortfolioRecommendation,
  PortfolioResponse,
  SkillSetManifest,
  SkillSetPlan,
  SkillSetReceipt,
  SkillSetsResponse,
  PromptSample,
  RecentActivityItem,
  SessionMeta,
  SkillReportPaginatedPayload,
  SkillReportPayload,
  SkillReportResponse,
  SkillTestingReadiness,
  SkillSummary,
  SyncPreferences,
  SkillUsageRecord,
  TelemetryRecord,
  TrustBucket,
  TrustFields,
  TrustState,
  TrustWatchlistEntry,
  UpdateDesktopScheduleRequest,
  UpdateRemoteLibraryRequest,
  CreateRemoteLibraryShareRequest,
  RemoteLibraryShare,
  RemoteLibraryShareArtifact,
  RemoteLibrarySharesResponse,
  ApplySkillSetRequest,
  PlanSkillSetRequest,
  RollbackSkillSetRequest,
  QuarantineReceipt,
  QuarantineRecord,
} from "@selftune/runtime/dashboard-contract";

export type { CreateCheckReadiness, CreateCheckState } from "@selftune/runtime/types";
